# Generated by Django 4.2.2 on 2023-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
