# Generated by Django 4.2.2 on 2023-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
