# Generated by Django 4.2.2 on 2023-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
