# Generated by Django 4.2.2 on 2023-10-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_paymenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
