"""
Django settings for edeypay project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
import os

from dotenv import load_dotenv
from pathlib import Path



load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mty!*vcy1&6o^bi)8h3rbw9#sc!mtd@1k=7ir3mwaqve-jmib'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'bootstrap4',
    'widget_tweaks',
    
    
    'account',
    'lottery',
    'lotteryx',
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use the URL of your preferred message broker (e.g., Redis)

# Example settings for task serialization, result backend, and other Celery options
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'



MIDDLEWARE = [
    # 'account.middleware.AccountBalanceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'edeypay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edeypay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configure background tasks to run asynchronously
BACKGROUND_TASK_RUN_ASYNC = True

# Define the schedule for the management command
BACKGROUND_TASKS = [
    {
        'name': 'path.to.generate_daily_lottery_data',  # Replace with the actual path to your command
        'schedule': timedelta(days=1, hours=8, minutes=5),  # Run daily at 8:05 am
    },
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

AUTH_USER_MODEL="account.User"
ACCOUNT_UNIQUE_EMAIL=True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

PAYSTACK_SECRET_KEY = os.environ['PAYSTACK_SECRET_KEY']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ['EMAIL_HOST'] # SMTP server
EMAIL_PORT = os.environ['EMAIL_PORT']  # Port for the SMTP server
EMAIL_USE_TLS = True  # Use TLS for secure communication
EMAIL_USE_SSL = False  # Use SSL (only one of TLS or SSL can be True)

EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']  # Your Zoho email address
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']  # Your Zoho email password or app-specific password
DEFAULT_FROM_EMAIL = os.environ['DEFAULT_FROM_EMAIL']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
