# Generated by Django 4.2.2 on 2023-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterydraw',
            name='winning_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
