# Generated by Django 4.2.2 on 2023-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0002_alter_lotterydraw_winning_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterydraw',
            name='winning_numbers',
            field=models.CharField(default='0,0,0,0,0', max_length=255),
        ),
    ]
