# Generated by Django 4.2.2 on 2023-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0003_alter_lotterydraw_winning_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryticket',
            name='amount_played',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
