# Generated by Django 4.2.2 on 2023-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0004_lotteryticket_amount_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotteryticket',
            name='is_winner',
        ),
    ]
