# Generated by Django 4.2.2 on 2023-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0007_alter_lotteryticket_amount_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryticket',
            name='amount_played',
            field=models.CharField(max_length=50),
        ),
    ]
