# Generated by Django 4.2.2 on 2023-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0008_alter_lotteryticket_amount_played'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotteryticket',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AddField(
            model_name='lotteryticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Win', 'Win'), ('Lose', 'Lose')], default='Pending', max_length=10),
        ),
    ]
