# Generated by Django 4.2.2 on 2023-10-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0009_alter_lotteryticket_options_lotteryticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotteryticket',
            name='status',
        ),
    ]
