# Generated by Django 4.2.2 on 2023-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0010_remove_lotteryticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryticket',
            name='is_winner',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Win', 'Win'), ('Lose', 'Lose')], default='Pending', max_length=10),
        ),
    ]
