# Generated by Django 4.2.2 on 2023-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteryx', '0011_lotteryticket_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
