# Generated by Django 4.2.2 on 2023-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryticket',
            name='amount_played',
            field=models.FloatField(default=0.0),
        ),
    ]
